import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";
import gitHub from "/public/Layer 3.png";
import gitHubHover from "/public/Layer 3Hover.png";
import linkedIn from "/public/Layer 4.png";
import linkedInHover from "/public/Layer 4Hover.png";
import unccImg from "/public/8716-01 Charlotte Master File v7_1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>{"Jacob's About Me"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.bar}>
          <ul>
            <li className={styles.navLine}>
              <Link className={styles.navLineText} href="/">
                {"<home>"}
              </Link>
            </li>
            <li className={styles.navLine}>
              <Link className={styles.navLineTextActive} href="about">
                {"<about>"}
              </Link>
            </li>
            <li className={styles.navLine}>
              <Link className={styles.navLineText} href="projects">
                {"<projects>"}
              </Link>
            </li>
            <li className={styles.navLineLast}>
              <Link
                className={styles.navImage}
                href="https://github.com/Voiduhh"
                title="Github"
                target="_blank"
              >
                <Image src={gitHub} />
                <Image src={gitHubHover} />
              </Link>
            </li>
            <li className={styles.navLineLast}>
              <Link
                className={styles.navImage}
                href="https://www.linkedin.com/in/jacobpikul/"
                target="_blank"
              >
                <Image src={linkedIn} />
                <Image src={linkedInHover} />
              </Link>
            </li>
          </ul>
        </div>
        <div className={styles.aboutContent}>
          <h1>About Me</h1>
          <p>
            I studied Computer Science at the University of North Carolina at
            Charlotte for a Bachelor of Arts. My expertise includes Java, HTML,
            CSS, Appian, a little Python, SQL, C#, React, React Native, NextJS,
            and JavaScript.
          </p>
          <Image src={unccImg} width={1331} height={400} />
        </div>
      </main>
    </>
  );
}
