import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jacob Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.bar}>
          <ul>
            <li className={styles.navLine}>
              <Link className={styles.navLineTextActive} href="/">
                {"<home>"}
              </Link>
            </li>
            <li className={styles.navLine}>
              <Link className={styles.navLineText} href="about">
                {"<about>"}
              </Link>
            </li>
            <li className={styles.navLine}>
              <Link className={styles.navLineText} href="projects">
                {"<projects>"}
              </Link>
            </li>
            <li className={styles.navLineLast}>
              <Link
                className={styles.navImage}
                href="https://github.com/Voiduhh"
                title="Github"
                target="_blank"
              >
                <img src="Layer 3.png" />
                <img src="Layer 3Hover.png" />
              </Link>
            </li>
            <li className={styles.navLineLast}>
              <Link
                className={styles.navImage}
                href="https://www.linkedin.com/in/jacobpikul/"
                target="_blank"
              >
                <img src="Layer 4.png" />
                <img src="Layer 4Hover.png" />
              </Link>
            </li>
          </ul>
        </div>
        <div className={styles.bodyContent}>
          <div className={styles.bodyText}>
            <a>Hello,</a>
            <h1>I'm Jacob</h1>
            <ul>
              <li>Appian Developer</li>
              <li>Full Stack Developer</li>
              <li>Avid Learner</li>
            </ul>
          </div>
          <div className={styles.bodyImage}>
            <img src="Keyboard.png" />
          </div>
        </div>
      </main>
    </>
  );
}
