import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";
import gitHub from "/public/Layer 3.png";
import gitHubHover from "/public/Layer 3Hover.png";
import linkedIn from "/public/Layer 4.png";
import linkedInHover from "/public/Layer 4Hover.png";
import websiteImage from "/public/website.jpg";
import ueImage from "/public/ue-logo-stacked-unreal-engine-w-677x545-fac11de0943f.png";
import reactImage from "/public/React-icon.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>{"Jacob's Projects"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.bar}>
          <ul>
            <li className={styles.navLine}>
              <Link className={styles.navLineText} href="/">
                {"<home>"}
              </Link>
            </li>
            <li className={styles.navLine}>
              <Link className={styles.navLineText} href="about">
                {"<about>"}
              </Link>
            </li>
            <li className={styles.navLine}>
              <Link className={styles.navLineTextActive} href="projects">
                {"<projects>"}
              </Link>
            </li>
            <li className={styles.navLineLast}>
              <Link
                className={styles.navImage}
                href="https://github.com/Voiduhh"
                title="Github"
                target="_blank"
              >
                <Image src={gitHub} width={35} />
                <Image src={gitHubHover} width={35} />
              </Link>
            </li>
            <li className={styles.navLineLast}>
              <Link
                className={styles.navImage}
                href="https://www.linkedin.com/in/jacobpikul/"
                target="_blank"
              >
                <Image src={linkedIn} width={35} />
                <Image src={linkedInHover} width={35} />
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h1 className={styles.header}>PROJECTS</h1>
        </div>
        <div className={styles.gridLayout}>
          <div className={styles.card}>
            Personal Website
            <p>
              This site itself is one of my projects! Helped me learn the basics
              of NextJS
            </p>
            <Image
              src={websiteImage}
              className={styles.imgSite}
              width={480}
              height={200}
            />
          </div>
          <div className={styles.card}>
            Game Development
            <p>
              Learning C++ and/or C# is the next task on my list for Game Dev
            </p>
            <Image
              className={styles.imgCenter}
              src={ueImage}
              width={340}
              height={200}
            />
          </div>
          <div className={styles.card}>
            Application Development
            <p>
              Start to learn React Native, Flutter, etc to build mobile
              applications
            </p>
            <Image
              className={styles.imgCenter}
              src={reactImage}
              width={230}
              height={220}
            />
          </div>
        </div>
      </main>
    </>
  );
}
