import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jacob Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.bar}>
          <ul>
            <li className={styles.navLine}>
              <Link className={styles.navLineText} href="/">
                {"<home>"}
              </Link>
            </li>
            <li className={styles.navLine}>
              <Link className={styles.navLineText} href="about">
                {"<about>"}
              </Link>
            </li>
            <li className={styles.navLine}>
              <Link className={styles.navLineTextActive} href="projects">
                {"<projects>"}
              </Link>
            </li>
            <li className={styles.navLineLast}>
              <Link
                className={styles.navImage}
                href="https://github.com/Voiduhh"
                title="Github"
                target="_blank"
              >
                <img src="Layer 3.png" />
                <img src="Layer 3Hover.png" />
              </Link>
            </li>
            <li className={styles.navLineLast}>
              <Link
                className={styles.navImage}
                href="https://www.linkedin.com/in/jacobpikul/"
                target="_blank"
              >
                <img src="Layer 4.png" />
                <img src="Layer 4Hover.png" />
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h1 className={styles.header}>PROJECTS</h1>
        </div>
        <div className={styles.gridLayout}>
          <div className={styles.card}>
            Personal Website
            <p>
              This site itself is one of my projects! Helped me learn the basics
              of NextJS
            </p>
            <img src="website.jfif" className={styles.imgSite} />
          </div>
          <div className={styles.card}>
            Game Development
            <p>
              Learning C++ and/or C# is the next task on my list for Game Dev
            </p>
            <img
              className={styles.imgCenter}
              src="ue-logo-stacked-unreal-engine-w-677x545-fac11de0943f.png"
            />
          </div>
          <div className={styles.card}>
            Application Development
            <p>
              Start to learn React Native, Flutter, etc to build mobile
              applications
            </p>
            <img className={styles.imgCenter} src="React-icon.png" />
          </div>
        </div>
      </main>
    </>
  );
}
